apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: prometheus-operator-crds
            repository:
                url: https://prometheus-community.github.io/helm-charts
            version: 25.0.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-prometheus-operator-crds-25.0.1-7956f4c63dbca1b0/data
      permissions: null
kind: Config
