apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - git:
            ref: v3.6.5
            url: https://github.com/traefik/traefik
          includePaths:
            - contrib/grafana/traefik-kubernetes.json
          lazy: true
          newRootPath: contrib
          path: .
      path: .myks/vendir-cache/git-traefik-v3.6.5-e7c996d3f0bc2f28/data
      permissions: null
kind: Config
