#@data/values
---
prototype:
  sources:
    argocd:
      helmChart:
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
        version: 9.3.3
    dashboards:
      git:
        ref: f30dcfa0758fb588215f2ea808cc30917db80365
        url: https://github.com/adinhodovic/argo-cd-mixin
      includePaths:
        - dashboards_out/argo-cd-*.json
      plugin: ytt
