#@data/values
---
prototype:
  sources:
    argocd:
      git:
        ref: v2.14.7
        url: https://github.com/argoproj/argo-cd
      includePaths:
        - manifests/install.yaml
      newRootPath: manifests
      plugin: ytt
