apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: traefik
            repository:
                url: https://traefik.github.io/charts
            version: 37.4.0
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-traefik-37.4.0-58394144d1378dd1/data
      permissions: null
kind: Config
