#@data/values
---
prototype:
  sources:
    k8s-monitoring:
      git:
        ref: v2.1.4
        url: https://github.com/grafana/k8s-monitoring-helm
      includePaths:
        - charts/k8s-monitoring-v1/**
      newRootPath: charts/k8s-monitoring-v1
