apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: prometheus-operator-crds
            repository:
                url: https://prometheus-community.github.io/helm-charts
            version: 18.0.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-prometheus-operator-crds-18.0.1-40d1f0850ca5e548/data
      permissions: null
kind: Config
