[settings]
# Required for the github backend
experimental = true

[tools]
"ubi:mykso/myks" = "5.5.1"
helm = "4.0.4"
kubeconform = "0.7.0"
sops = "3.11.0"
task = "3.44.0"
yq = "4.50.1"
argocd = "3.2.3"
