#@data/values
---
prototype:
  sources:
    cert-manager:
      helmChart:
        url: https://charts.jetstack.io
        version: v1.19.2
    monitoring:
      helmChart:
        name: cert-manager-monitoring
        url: https://charts.adfinis.com
        version: 0.3.1
