#@data/values
---
prototype:
  sources:
    vmks:
      helmChart:
        name: victoria-metrics-k8s-stack
        url: oci://ghcr.io/victoriametrics/helm-charts
        version: 0.67.0
    prom-crds:
      helmChart:
        name: prometheus-operator-crds
        url: https://prometheus-community.github.io/helm-charts
        version: 26.0.0
