apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.0
overrides:
- image: docker.io/traefik:v3.6.5
  newImage: oci.zebradil.dev/index.docker.io-cache/library/traefik@sha256:67622638cd88dbfcfba40159bc652ecf0aea0e032f8a3c7e3134ae7c037b9910
  preresolved: true
