apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
    - image: docker.io/traefik:v3.6.7
      newImage: oci.zebradil.dev/index.docker.io-cache/library/traefik:v3.6.7
    - image: registry.access.redhat.com/ubi8/ubi:8.9
      newImage: oci.zebradil.dev/registry.access.redhat.com-cache/ubi8/ubi:8.9
