apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/traefik
  contents:
  - path: .
    lazy: true
    helmChart:
      name: traefik
      version: 38.0.1
      repository:
        url: https://traefik.github.io/charts
