apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/traefik
  contents:
  - path: .
    lazy: true
    helmChart:
      name: traefik
      version: 38.0.1
      repository:
        url: https://traefik.github.io/charts
- path: ytt/dashboard
  contents:
  - path: .
    lazy: true
    git:
      url: https://github.com/traefik/traefik
      ref: v3.6.5
    includePaths:
    - contrib/grafana/traefik-kubernetes.json
    newRootPath: contrib
