#@ load("@ytt:data", "data")
#@ load("traefik.lib.yaml", "route")

#@ for/end route_doc in route.default("grafana", "vmks-grafana"):
--- #@ route_doc

#@ for/end route_doc in route.default("alertmanager", "vmalertmanager-vmks"):
--- #@ route_doc

#@ for component in ["vmalert", "vmagent", "vmsingle"]:
#@   for/end route_doc in route.default(component, component + "-vmks"):
--- #@ route_doc
#@ end
