#@ load("@ytt:data", "data")
#@ load("traefik.lib.yaml", "route")

#@ for/end route_doc in route.default("grafana", "vmks-grafana"):
--- #@ route_doc

#@ for/end route_doc in route.default("alertmanager", "vmalertmanager-vmks"):
--- #@ route_doc

#@ for/end route_doc in route.default("victoria-metrics", "vmsingle-vmks"):
--- #@ route_doc
