#@data/values
---
prototype:
  sources:
    postgresql:
      helmChart:
        url: oci://registry-1.docker.io/bitnamicharts
        version: 18.3.0
    redis:
      helmChart:
        url: oci://registry-1.docker.io/bitnamicharts
        version: 24.1.8
