#@data/values
---
prototype:
  sources:
    traefik:
      helmChart:
        url: https://traefik.github.io/charts
        version: 39.0.2
    dashboard:
      git:
        ref: v3.6.6
        url: https://github.com/traefik/traefik
      includePaths:
        - contrib/grafana/traefik-kubernetes.json
      newRootPath: contrib
      plugin: ytt
