adminPassword: ENC[AES256_GCM,data:v97yC19MEzlc7ItAYB0Dpphitg==,iv:SbIeYEkL4SxVOFbWcX7Q+OHtMzJhWqFS+D82IajWoho=,tag:p3mp6CaFSjiiaNmqdePljg==,type:str]
sops:
    age:
        - recipient: age13hxx3dgpjcp0v2z5xx07nwm4zvdy78rc9xra6lujzzrl7c657ekq2vgwnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUF1TWtlRStpZWVHTnM3
            WHFqejloREdiNXlmNVAvcGxoY3hFVXhSQ1NZCnFzUzBlQW1PK0tVSmlGZGtFS3p5
            UDFaNmtCeWdYRUtLQk8zSHExb3FmRkEKLS0tIGFSOUNxYXdPRjNaSHdzak5sbURZ
            cEs0MW9PTW93ZDloanFXTk9DUXJ6T1UKDutancYu/k3fdAcUu43Wz3JlEi/d1Vr8
            zlWdlXflE9H312ws9L6Qem58Ku/UkU6rlp+Nz9/ZQ1iGbLH80PFu0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age188h98rs643kglmetvqt3hhnllw0ga45jg94p8xar2qe0c987k59q9qxv3v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VW9MUi8yQjNid2dsL2Zp
            TTNHUExKTmExbUlKa1JHYjBUSVV4SWlsbDNVCmlvSmhHRlhNYmZwWGNvRVVwS1M3
            RUVzUUY3SkNMMjNaWlg5NnVicHRZc3cKLS0tICtWR2JReHUrd0w3RUwvci9SZUY5
            YTRoc3FaaFpweGxNNnh2R3hha0UvL00KQ1ZR61jt1ro243U7z0SbN5/BFFMsJhrv
            uv9zGGjwZSLKwYjiAvP1meoRj+eucOUEAXbmag8OUc8bJDgDYyW84Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13vh8ef8lgqfgr7aljd2y9c82syxlf7u35lxwrr9yxlhrhjdxfptsc9uk7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0xUR3FlMTQ5dm01aEF0
            Q1F4Nm92YXVubDNrdmxBMVdVTXlFS1JmZURrCktrSS84MCtyODVlaythaWxVK3JZ
            U3VpK09uU1dhU1krZk1oSzVMcmkrbHMKLS0tIGVTY1FWOUNKcTNkSUdOWUdhbHZr
            bDhXSSt3UjJnam5YRE43cE4zdGptdDAKSNkvfUYcrQt2IhOcbCjrQte23ZoDquks
            uuwuI8je+4enrfGcYoYkDM/+4HW5k23b4glzlXu5i2B0/w8VeALnPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T01:34:04Z"
    mac: ENC[AES256_GCM,data:mwVnBv5s5urKeGyDR0eG7VMJtBgJONMcSrJs5SIdG8ldAFAIMntVlNwl6UXxkzBFuqZikNm/FynhI6tZM7vN2bb3/r9HJQmRUTXCmZYhRtElTzfHCEakVVXhsjY43MbJbq8/w+lSKypIWMrVAp6LCtS7Qtd8R0vx1J2xLgWtX0g=,iv:vOEpMEP0Lrr+DTEHVIxTzC82KQOn3WCyFFcEayHXaZ0=,tag:0VklUDS6OYEqzNYQpKxzXg==,type:str]
    encrypted_regex: .
    version: 3.11.0
