apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.47.0
overrides:
- image: docker.io/curlimages/curl:8.9.1
  newImage: oci.zebradil.dev/index.docker.io-cache/curlimages/curl@sha256:8addc281f0ea517409209f76832b6ddc2cabc3264feb1ebbec2a2521ffad24e4
  preresolved: true
- image: docker.io/grafana/grafana:12.3.0
  newImage: oci.zebradil.dev/index.docker.io-cache/grafana/grafana@sha256:70d9599b186ce287be0d2c5ba9a78acb2e86c1a68c9c41449454d0fc3eeb84e8
  preresolved: true
- image: docker.io/library/busybox:1.31.1
  newImage: oci.zebradil.dev/index.docker.io-cache/library/busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
  preresolved: true
